version: '3'
services:
  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_net
    env_file: .env
    expose:
      - 3306

  app:
    image: $DOCKER_USER/$IMAGE
    container_name: app
    restart: always
    env_file: .env
    entrypoint: ./boot.sh
    networks:
      - backend_net
      - frontend_net
    depends_on:
      - db

  proxy:
    image: $DOCKER_USER/proxy:latest
    container_name: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - frontend_net

volumes:
  db_data:


networks:
  frontend_net:
  backend_net:
