"""new taipei city table

Revision ID: 1186991ea78c
Revises: 
Create Date: 2022-08-08 15:16:10.854133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1186991ea78c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_taipei_city',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('district', sa.String(length=8), nullable=False),
    sa.Column('object_of_transaction', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('total_floor_numbers', sa.String(length=2), nullable=False),
    sa.Column('building_state', sa.String(length=16), nullable=False),
    sa.Column('main_use', sa.String(length=16), nullable=False),
    sa.Column('land_total_area', sa.Float(), nullable=False),
    sa.Column('building_total_area', sa.Float(), nullable=False),
    sa.Column('room', sa.String(length=1), nullable=False),
    sa.Column('restaurant_and_living_room', sa.String(length=1), nullable=False),
    sa.Column('bathroom', sa.String(length=1), nullable=False),
    sa.Column('build_name', sa.String(length=32), nullable=False),
    sa.Column('buildings', sa.String(length=32), nullable=False),
    sa.Column('parking_sapce_type', sa.String(length=8), nullable=False),
    sa.Column('parking_sapce_total_area', sa.Float(), nullable=False),
    sa.Column('parking_sapce_price', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_taipei_city_build_name'), 'new_taipei_city', ['build_name'], unique=False)
    op.create_index(op.f('ix_new_taipei_city_district'), 'new_taipei_city', ['district'], unique=False)
    op.create_index(op.f('ix_new_taipei_city_transaction_date'), 'new_taipei_city', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_taipei_city_transaction_date'), table_name='new_taipei_city')
    op.drop_index(op.f('ix_new_taipei_city_district'), table_name='new_taipei_city')
    op.drop_index(op.f('ix_new_taipei_city_build_name'), table_name='new_taipei_city')
    op.drop_table('new_taipei_city')
    # ### end Alembic commands ###
