"""deals table

Revision ID: 3317c2a81728
Revises: 
Create Date: 2022-08-08 21:51:28.841456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3317c2a81728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('city', sa.String(length=3), nullable=False),
                    sa.Column('district', sa.String(length=8), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_deals_city'), 'deals', ['city'], unique=False)
    op.create_index(op.f('ix_deals_district'), 'deals', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_district'), table_name='deals')
    op.drop_index(op.f('ix_deals_city'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
