"""empty message

Revision ID: 8eb5ad366765
Revises: 8789035fea99
Create Date: 2022-09-19 22:02:07.685713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb5ad366765'
down_revision = '8789035fea99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_statistics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('city', sa.String(length=3), nullable=False),
                    sa.Column('district', sa.String(length=8), nullable=False),
                    sa.Column('year', sa.String(length=4), nullable=False),
                    sa.Column('month', sa.String(length=2), nullable=False),
                    sa.Column('build_name', sa.String(length=32), nullable=False),
                    sa.Column('room', sa.String(length=1), nullable=False),
                    sa.Column('count_num', sa.Integer(), nullable=False),
                    sa.Column('avg_total_price', sa.Integer(), nullable=False),
                    sa.Column('avg_house_price', sa.Integer(), nullable=False),
                    sa.Column('avg_house_unit_price', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('city', 'district', 'year', 'month', 'build_name',
                                        'room', name='uc_city_district_year_month_buildname_room')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_statistics')
    # ### end Alembic commands ###
